version: '3.8'

services:
  nginx:
    container_name: drf_2fa_auth_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - media:/code/media
      - static:/code/static
    depends_on:
      - api
    networks:
      - default_network
    restart: unless-stopped

  api:
    container_name: drf_2fa_auth_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/code/static
      - media:/code/media
      - logs:/code/logs
    depends_on:
      - redis
      - db
    networks:
      - default_network
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG:-false}

  redis:
    image: redis:latest
    container_name: drf_2fa_auth_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default_network
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: drf_2fa_auth_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default_network
    restart: unless-stopped

volumes:
  pgdata: { }
  media: { }
  static: { }
  logs: { }

networks:
  default_network: { }
